# Generated by Django 6.0.2 on 2026-03-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('posicao', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='players/')),
            ],
        ),
    ]
